FROM node:18-alpine

WORKDIR /app

RUN chown -R node:node /app

USER node

COPY package.json yarn.lock* package-lock.json* ./

RUN yarn install && yarn global add vite

COPY . .

EXPOSE 5173

CMD ["yarn", "run", "dev"]
