version: '3.9'

services:
  frontend:
    container_name: frontend
    image: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - 5173:5173
    environment:
      - VITE_APP_API_URL=http://localhost:5173
    restart: always
    depends_on:
      - backend
      
  backend:
    container_name: backend
    image: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: my_db
      NAME: FarmingAssistant
    depends_on:
      - mongo_db

  mongo_db:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db

volumes:
  mongo_db: {}