FROM node:20.17-alpine

RUN apk add --no-cache python3 make g++ && \
    apk del python3 make g++ && \
    rm -rf /var/cache/apk/*

ARG NODE_ENV=production  

WORKDIR /app

RUN addgroup app && adduser -S -G app app

COPY package*.json ./

RUN yarn install --production --frozen-lockfile

COPY --chown=app:app . .

USER app

EXPOSE 5000

CMD ["yarn", "start"]